name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        image: [cli, semver, postgres]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build {{matrix.image}}
        run: docker build . --file ${{matrix.image}}/Dockerfile --tag ${{matrix.image}}:$(date +%s)
