name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        image: [ cli, semver, postgres ]
    env:
      # github.owner as <owner>/<sub dir>
      IMAGE_NAME: ${{ github.repository_owner }}/${{ matrix.image }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ env.IMAGE_NAME }}
        run: docker build . --file ${{ matrix.image }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
